<a href="https://colab.research.google.com/github/sonal-jharkharia/Python_Fundamental_Training/blob/main/Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numerical Operations on Numpy

In [ ]:
import numpy as np

In [ ]:
# Basic Scalar Operations
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [ ]:
# Matrix Multiplications
c = np.diag([1, 2, 3, 4])
print(c*c)
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [ ]:
# Comparison
a = np.array([1, 2, 3, 4])
b = np.array([1, 3, 2, 4])
np.array_equal(a, b)

False

In [ ]:
# Logical Operations
a = np.array([1, 1, 0, 0], dtype='bool')
b = np.array([1, 0, 1, 0], dtype='bool')
np.logical_or(a, b)

array([ True,  True,  True, False])

In [ ]:
# Transcendental Functions
a = np.arange(4)
print(a)
np.exp(a)

[0 1 2 3]


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [ ]:
# Computing Sum
a = np.array([2, 3, 1])
print(np.sum(a))

x = np.array([[1, 1], [2, 2]])
x.sum(axis=0) # Sum along column
x.sum(axis=1) # Sum along rows

6


array([2, 4])

In [ ]:
# Identifying minimum and maximum element of an array
a = np.array([1, 34, 45 ,2])
a.min()# min/max value and its index value
a.max()
a.argmin()
a.argmax()

2

In [ ]:
# Logical operations
x = np.zeros((3, 3))
np.any(x != 0)

False

In [ ]:
a = np.array([1, 4, 3])
b = np.array([2, 3, 4])
print(a<=b)
(a<=b).all()

[ True False  True]


False

In [ ]:
# Statistics
x = np.array([2, 1, 3, 0])
print(x.mean())# mean
print(np.median(x))# median
print(x.std())# standard deviation

y = np.array([[1, 2, 3], [4, 5, 6]])
print(y)
np.median(y, axis=1)# Row wise median

1.5
1.5
1.118033988749895
[[1 2 3]
 [4 5 6]]


array([2., 5.])

In [ ]:
# Flattening
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
a.ravel()
print(a.T)
a.T.ravel()


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


array([1, 4, 2, 5, 3, 6])

In [ ]:
# Reshaping
print(a)
b = a.ravel()
print(b)
b = b.reshape((3, 2))
print(b)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Sorting Data
a = np.array([[5, 4], [2, 3]])
print(a)
b = np.sort(a, axis=1)

j = np.argsort(a)
print(j)

[[5 4]
 [2 3]]
[[1 0]
 [0 1]]
