<a href="https://colab.research.google.com/github/sonal-jharkharia/Python_Fundamental_Training/blob/main/Programming_drill_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Drill #29

<img src="https://drive.google.com/uc?id=109gQ0yPiTdJ6cBQiL1zyKiH2MD5LKTET" width="700">

# Expected Output
<img src="https://drive.google.com/uc?id=1BhfG7oMzjDH685GbvW2h8b3bKhqkQeSC" width="700">


In [ ]:
# Write your own code  here

# Drill #30


<img src="https://drive.google.com/uc?id=1y7J8HlclDc_200W1oYBVtr3l-66B_2hv" width="700">

# Expected Output
<img src="https://drive.google.com/uc?id=1HPkRafcIsT7vLp8_2rR5blhjblQZJ450" width="600">

In [ ]:
# Write your own code here

# Drill #31

<img src="https://drive.google.com/uc?id=1MEhGhXS_OC1ZisPbEGQonYcoadzvlKZZ" width="700">
<img src="https://drive.google.com/uc?id=1R24HyNqLMt8j5u3pABKpGlCDnjgUqrX9" width="1000">


# Expected Output
<img src="https://drive.google.com/uc?id=1eqiocySYtWeWuD7NV8plOjubjg0waTRC" width="700">

In [ ]:
# Write your own code here

##Drill #32
<img src="https://drive.google.com/uc?id=11LGUssKKIP6RSXx_fnMWMMMxrOLoLQu2" width="800">

###Expected Output
<img src="https://drive.google.com/uc?id=17R7LrG_YhIIYJKpxKjKsLm22gt4jYtHn" width="600">


a1: 
 [[1 2 3]
 [4 5 6]] 
 a2: 
 [[10 20 30]
 [40 50 60]]
----------------------------------------------------------------------
Horizontal stacking: 
 [[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
Shape of array after horizontal stacking:  (2, 6)
----------------------------------------------------------------------
Vertical stacking: 
 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
Shape of array after vertical stacking:  (4, 3)
